# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170612_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='athors',
            new_name='authors',
        ),
    ]
