# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_review_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='review_by',
            new_name='reviewed_by',
        ),
    ]
